Repository openshift/release-controller, pull requests merged in 2019-02, with the labels that each got.

#23 Start prow jobs in the proper state
  cmd/release-controller/sync.go
Labels: approved, lgtm

#20 README.md: New file
  README.md
Labels: approved, lgtm, size/XS

#24 Switch back to 'payload' in the fake image graph
  cmd/release-controller/graph.go
Labels: approved, lgtm, size/XS

#25 Clear scheduled flag when create image stream mirror
  cmd/release-controller/sync.go
Labels: approved, lgtm, size/XS

#26 Fix unclosed HTML tag
  cmd/release-controller/http.go
Labels: approved, lgtm

#27 Sort releases by their config name in status page
  cmd/release-controller/http.go
Labels: approved, lgtm, size/XS

#28 Support publishing an image stream after verification
  cmd/release-controller/main.go
  cmd/release-controller/release.go
  cmd/release-controller/sync.go
  cmd/release-controller/types.go
Labels: approved, lgtm, size/L
