Repository openshift/release-controller, pull requests merged in 2019-05, with the labels that each got.

#87 Add additional prerelease-* and nightly-* handlers
  cmd/release-controller/http_upgrade_graph.go
Labels: approved, lgtm, size/S

#90 Add additional ?format support for `api/v1/.../latest`
  cmd/release-controller/http.go
Labels: approved, lgtm, size/L

#91 Allow relative lookups of latest via `?rel=N`
  cmd/release-controller/http.go
Labels: approved, lgtm, size/M

#93 rel=N should work without a constraint
  cmd/release-controller/http.go
Labels: approved, lgtm, size/XS

#94 Correctly include other releases as compare targets
  cmd/release-controller/http.go
  cmd/release-controller/http_helper_test.go
Labels: approved, lgtm, size/M

#95 External edges cause some upgrade edges to be omitted visually
  cmd/release-controller/http_helper.go
  cmd/release-controller/http_helper_test.go
Labels: approved, lgtm, size/L

#96 Make external upgrades have color
  cmd/release-controller/http_helper.go
Labels: approved, lgtm, size/XS

#97 Fix another bug in external name splitting
  cmd/release-controller/http_helper.go
  cmd/release-controller/http_helper_test.go
Labels: approved, lgtm, size/S

#98 cmd/release-controller/http: Add id anchors to "Upgrades from" and "Upgrades to"
  cmd/release-controller/http.go
Labels: approved, lgtm, size/XS
