Repository openshift/release-controller, pull requests merged in 2019-07, with the labels that each got.

#102 Extend relative time intervals for better precision
  cmd/release-controller/http.go
Labels: approved, lgtm, size/S

#101 Link to Version Promoted from
  cmd/release-controller/http.go
Labels: approved, lgtm, size/XS

#106 Increase storage for git cache
  cmd/release-controller/info.go
Labels: approved, lgtm, size/XS

#103 Candidate endpoint
  cmd/release-controller/http.go
  cmd/release-controller/http_candidate.go
  cmd/release-controller/info.go
  cmd/release-controller/types.go
Labels: approved, lgtm, size/XL

#108 Release candidate link fix
  cmd/release-controller/http_candidate.go
Labels: approved, lgtm, size/XS
