Repository openshift/release-controller, pull requests merged in 2023-02, with the labels that each got.

#491 OCPCRT-74: redux
  cmd/release-controller-api/http.go
  cmd/release-controller-api/http_changelog.go
  cmd/release-controller-api/http_compare.go
  cmd/release-controller/sync.go
  go.mod
  go.sum
  pkg/release-controller/release_info.go
  pkg/release-controller/types.go
  pkg/rhcos/rhcos.go
  vendor/github.com/opencontainers/go-digest/.mailmap
  vendor/github.com/opencontainers/go-digest/.pullapprove.yml
  vendor/github.com/opencontainers/go-digest/.travis.yml
  vendor/github.com/opencontainers/go-digest/CONTRIBUTING.md
  vendor/github.com/opencontainers/go-digest/LICENSE
  vendor/github.com/opencontainers/go-digest/LICENSE.docs
  vendor/github.com/opencontainers/go-digest/MAINTAINERS
  vendor/github.com/opencontainers/go-digest/README.md
  vendor/github.com/opencontainers/go-digest/algorithm.go
  vendor/github.com/opencontainers/go-digest/digest.go
  vendor/github.com/opencontainers/go-digest/digester.go
  vendor/github.com/opencontainers/go-digest/doc.go
  vendor/github.com/opencontainers/go-digest/verifiers.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#493 Enabling difference version links for `/changelog` API
  cmd/release-controller-api/http.go
Labels: lgtm, approved

#494 Add releasestream endpoints for rejected releases and all releases
  cmd/release-controller-api/http.go
Labels: lgtm, approved

#495 Fix logic for all releases api endpoint
  cmd/release-controller-api/http.go
Labels: lgtm, approved

#492 add jira fetch
  cmd/release-controller-api/main.go
  cmd/release-controller/main.go
  pkg/release-controller/release_info.go
Labels: lgtm, approved, tide/merge-method-squash

#497 Updating the RHCoS Release Browser links
  pkg/rhcos/rhcos.go
Labels: lgtm, approved

#498 Updating RHCoS release browser logic
  pkg/rhcos/rhcos.go
  pkg/rhcos/rhcos_test.go
Labels: lgtm, approved
