Repository openshift/release-controller, pull requests merged in 2024-02, with the labels that each got.

#596 Adding support for a version prefix to the latest API
  cmd/release-controller-api/http.go
  cmd/release-controller/sync_verify.go
  pkg/release-controller/release.go
Labels: lgtm, approved

#595 http: add collapse support for all imagestreams
  cmd/release-controller-api/http.go
  cmd/release-controller-api/http_helper.go
  cmd/release-controller-api/static/htmlPageEndScripts.tmpl
  cmd/release-controller-api/static/releasePageHtml.tmpl
  cmd/release-controller-api/static/releaseStreamPageHtml.tmpl
Labels: lgtm, approved, tide/merge-method-squash

#593 Add Demo links on `Feature Based` release page
  cmd/release-controller-api/http.go
  cmd/release-controller-api/static/featureRelease.html
  pkg/release-controller/release_info.go
Labels: lgtm, approved

#597 Asking for input from users of the Files Cache
  pkg/release-controller/release_info.go
Labels: lgtm, approved

#598 Adding retry support to the Aggregator job
  cmd/release-controller/sync_verify_prow.go
  cmd/release-controller/sync_verify_prow_test.go
Labels: lgtm, approved

#600 TRT-1504: Pin gcp release jobs to gcp build clusters
  cmd/release-controller/sync_verify_prow.go
Labels: lgtm, approved, jira/valid-reference

#602 Allow changelogs with missing commits
  pkg/release-controller/release_info.go
Labels: lgtm, approved

#604 update `test-infra` dependency
  go.mod
  go.sum
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/types.go
  vendor/k8s.io/test-infra/prow/apis/prowjobs/v1/zz_generated.deepcopy.go
  vendor/k8s.io/test-infra/prow/config/README.md
  vendor/k8s.io/test-infra/prow/config/branch_protection.go
  vendor/k8s.io/test-infra/prow/config/config.go
  vendor/k8s.io/test-infra/prow/config/prow-config-documented.yaml
  vendor/k8s.io/test-infra/prow/config/tide.go
  vendor/k8s.io/test-infra/prow/config/zz_generated.deepcopy.go
  vendor/k8s.io/test-infra/prow/gcsupload/run.go
  vendor/k8s.io/test-infra/prow/github/README.md
  vendor/k8s.io/test-infra/prow/github/app_auth_roundtripper.go
  vendor/k8s.io/test-infra/prow/github/client.go
  vendor/k8s.io/test-infra/prow/io/opener.go
  vendor/k8s.io/test-infra/prow/pjutil/pjutil.go
  vendor/k8s.io/test-infra/prow/plugins/README.md
  vendor/k8s.io/test-infra/prow/plugins/config.go
  vendor/k8s.io/test-infra/prow/plugins/plugin-config-documented.yaml
  vendor/k8s.io/test-infra/prow/pod-utils/clone/clone.go
  vendor/k8s.io/test-infra/prow/pod-utils/gcs/upload.go
  vendor/modules.txt
Labels: lgtm, approved

#605 Exclude `MultiJobAnalysis` jobs from stable release verification jobs
  pkg/release-controller/release.go
Labels: lgtm, approved
